# Generated by Django 5.2.16 on 2026-08-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('education_officer', 'Education Officer'), ('finance_officer', 'Finance Officer')], max_length=20),
        ),
    ]
