# Generated by Django 5.2.16 on 2026-08-15 11:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_teacherclassassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('session_datetime', models.DateTimeField()),
                ('session_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.courseclass')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('course_class', 'session_number'), name='unique_active_session_number_per_course_class')],
            },
        ),
    ]
