# Generated by Django 5.2.16 on 2026-08-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_coursesession_conducted_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='courseclass',
            name='unique_course_class_code_per_school_term',
        ),
        migrations.RemoveConstraint(
            model_name='school',
            name='unique_school_name_address',
        ),
        migrations.AddConstraint(
            model_name='courseclass',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('school', 'term', 'class_code'), name='unique_active_course_class_code_per_school_term'),
        ),
        migrations.AddConstraint(
            model_name='school',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'address'), name='unique_active_school_name_address'),
        ),
    ]
